[tool.autoflake]
exclude                   = ['__init__.py']
expand-star-imports       = true
in-place                  = true
recursive                 = true
remove-all-unused-imports = true
remove-duplicate-keys     = true
remove-unused-variables   = true

[tool.black]
color          = true
line-length    = 88
target-version = ["py38"]

[tool.isort]
atomic       = true
color_output = true
float_to_top = true
profile      = 'black'
py_version   = 38

[tool.pylint.format]
disable         = 'E0401,C0116,R0913'
max-line-length = '88'
